version: '3'
services:
  node:
    restart: always
    build: .
    env_file: ./.env
    ports:
      - "5555:5555"
    volumes:
      - ./:/code
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  mongo-express: 
    container_name: mongo-express
    image: mongo-express
    ports: 
    - '8083:8081'
volumes:
 mongodb: 